[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
project_5_capstone = "Hirm3Q5vTf2bTc83NMEfe8hjpdKrw6tdwK7DrjHnGR9Q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899/"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
