[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "4jQCoESTtvg1NZ55hfRcST3DFT28noSxnY7czNMHAVRT"

[registry]
url = "https://api.devnet.solana.com "

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"
